service: notes-app-api

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack
  - serverless-offline

# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ap-southeast-2

  environment:
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}
    NAME: ${file(../.env.yml):NAME}
    SALT: ${file(../.env.yml):SALT}
    PASSWORD: ${file(../.env.yml):PASSWORD}
    STORAGE_BUCKET: aserver-${self:provider.stage}-storage

  iamRoleStatements:
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: "arn:aws:s3:::${self:provider.environment.STORAGE_BUCKET}/*"
    - Effect: Allow
      Action:
        - "s3:CreateBucket"
      Resource: "arn:aws:s3:::*"

functions:
  getnote:
    handler: src/handler.getNote
    events:
      - http:
          path: note
          method: GET
  savenote:
    handler: src/handler.saveNote
    events:
      - http:
          path: note
          method: POST
